# Generated by Django 5.1.4 on 2024-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_offer_packages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
